apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vectorsphere-services
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: checkpoint-uploader
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
