apiVersion: v1
kind: Service
metadata:
  name: checkpoint-uploader-metrics
  labels:
    app: checkpoint-uploader
spec:
  selector:
    app: checkpoint-uploader
  type: ClusterIP
  ports:
    - name: metrics
      port: 8001
      targetPort: 8001
